require("euclidthedark.copilot")
require("euclidthedark.remap")
require("euclidthedark.editor")
require("euclidthedark.lazy")
require("euclidthedark.gruvbox")
require("euclidthedark.telescope")
require("euclidthedark.lsp")
require("euclidthedark.tree_sitter")
